import PageHero from "@/components/PageHero";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Certified AI Foundations Professional (CAFP) | Next Horizon AI Academy',
  description: 'Learn about the Certified AI Foundations Professional (CAFP) credential, an academy-issued certification recognizing foundational AI knowledge and practical skill.',
};

export default function CertificationsPage(){return <><PageHero eyebrow="Certification" title="Certified AI Foundations Professional (CAFP)" description="A Next Horizon AI Academy completion credential being developed to recognize learners who demonstrate foundational understanding and practical use of artificial intelligence."/><section className="bg-horizon-cloud py-20 sm:py-28"><div className="container-page"><div className="grid gap-8 lg:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-bold text-horizon-navy">Knowledge</h2><p className="mt-3 text-slate-600">Understand core AI concepts, capabilities, limitations, and common applications.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-bold text-horizon-navy">Application</h2><p className="mt-3 text-slate-600">Use prompting and practical workflows to solve everyday and business problems.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-bold text-horizon-navy">Responsibility</h2><p className="mt-3 text-slate-600">Recognize the importance of verification, privacy, ethics, and human judgment.</p></article></div><div className="mt-10 rounded-2xl bg-horizon-navy p-8 text-white sm:p-10"><h2 className="text-2xl font-extrabold">Credential transparency matters</h2><p className="mt-4 max-w-3xl leading-relaxed text-slate-200">CAFP is an academy-issued credential and is not presented as a government license or an accredited university degree. Final assessment, completion, and verification standards will be published before certification enrollment opens.</p></div></div></section></>}
