import type { Metadata } from "next";
import PageHero from "@/components/PageHero";
import PartnershipCTA from "@/components/partnerships/PartnershipCTA";
export const metadata: Metadata = { title: "Salesforce & Agentforce Career Pathway | Next Horizon AI Academy", description: "A planned independent learning pathway from CRM and responsible AI foundations to Agentforce projects and certification preparation." };
const levels=[
  ["Level 1", "Salesforce & CRM Foundations", "Customer 360 concepts, CRM terminology, data models, reports, dashboards, and responsible data use."],
  ["Level 2", "Agentforce Foundations", "Agent concepts, topics, actions, instructions, grounding, guardrails, testing, and human escalation."],
  ["Level 3", "Agentforce Career Lab", "Discovery, process mapping, solution documentation, portfolio projects, evaluation, and deployment planning."],
  ["Level 4", "Certification Preparation", "Structured study support aligned to the current Salesforce Certified Agentforce Specialist exam objectives."],
];
export default function AgentforcePathwayPage(){return <><PageHero eyebrow="Career Pathway • Coming Soon" title="Salesforce & Agentforce Career Pathway" description="A planned pathway that connects platform fundamentals, responsible agent design, applied projects, and preparation for the Salesforce Certified Agentforce Specialist credential."/><section className="bg-white py-20"><div className="container-page"><div className="grid gap-6 md:grid-cols-2">{levels.map(([level,title,body])=><article key={level} className="rounded-2xl border border-slate-200 p-7"><p className="text-sm font-bold uppercase tracking-[0.16em] text-horizon-blue">{level}</p><h2 className="mt-2 text-2xl font-bold text-horizon-navy">{title}</h2><p className="mt-3 leading-7 text-slate-600">{body}</p></article>)}</div></div></section><section className="bg-horizon-cloud py-20"><div className="container-page grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold text-horizon-navy">Instructor credential target</h2><p className="mt-5 leading-8 text-slate-600">The Academy&rsquo;s first selected Salesforce credential is Salesforce Certified Agentforce Specialist. The pathway will launch only when qualified instruction, current learning resources, hands-on access, and clear learner disclosures are in place.</p></div><aside className="rounded-2xl bg-white p-7"><h2 className="text-xl font-bold text-horizon-navy">Important credential disclosure</h2><p className="mt-3 leading-7 text-slate-600">Next Horizon AI Academy is an independent education provider. Academy completion certificates are not Salesforce certifications. Salesforce credentials are awarded only by Salesforce after a candidate meets its current exam requirements. No Salesforce affiliation or endorsement is implied.</p></aside></div></section><PartnershipCTA title="Sponsor or collaborate on an Agentforce career pathway"/></>}
