import type { Metadata } from "next";
export const metadata:Metadata={title:"AI Foundations + Adoption Pilot | Next Horizon AI Academy",description:"A focused organizational pilot combining AI readiness, workforce enablement, use-case discovery, workflow planning, and measurable adoption recommendations."};

const phases = [
  ["Baseline", "AI readiness assessment and stakeholder discovery establish the current state, goals, approved tools, risks, and adoption barriers."],
  ["Enable", "Participants build practical AI foundations, prompting, verification, responsible-use habits, and role-relevant confidence."],
  ["Apply", "The team identifies priority use cases and develops at least one reusable prompt, AI workflow, agent concept, or implementation-ready process map."],
  ["Roadmap", "Next Horizon summarizes outcomes, adoption gaps, pilot findings, and recommended next steps for implementation or broader rollout."],
];

export default function Page(){return <>
<section className="bg-horizon-cloud py-20"><div className="container-page max-w-5xl"><p className="font-bold uppercase tracking-wider text-horizon-blue">Corporate Pilot</p><h1 className="mt-4 text-4xl font-extrabold text-horizon-navy sm:text-5xl">AI Foundations + Adoption Pilot</h1><p className="mt-5 max-w-4xl text-lg leading-relaxed text-slate-600">A focused engagement for organizations that want to build shared AI capability, identify practical use cases, and leave with a clearer path from learning to implementation.</p></div></section>
<section className="bg-white py-20"><div className="container-page"><div className="grid gap-5 lg:grid-cols-4">{phases.map(([title,copy],i)=><article key={title} className="rounded-2xl border border-slate-200 p-6"><p className="text-sm font-bold text-horizon-blue">PHASE {i+1}</p><h2 className="mt-2 text-xl font-bold text-horizon-navy">{title}</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">{copy}</p></article>)}</div></div></section>
<section className="bg-horizon-cloud py-20"><div className="container-page grid gap-10 lg:grid-cols-2"><div><h2 className="text-3xl font-extrabold text-horizon-navy">Pilot outcomes</h2><ul className="mt-6 space-y-4 text-slate-700"><li>✓ Establish a measurable AI-readiness baseline.</li><li>✓ Build employee confidence with approved AI use.</li><li>✓ Apply the HORIZON Prompt Method™ to workplace tasks.</li><li>✓ Strengthen verification and responsible-use habits.</li><li>✓ Identify and prioritize practical business use cases.</li><li>✓ Map at least one reusable workflow, agent concept, or implementation candidate.</li><li>✓ Define recommended next steps for adoption or deployment.</li></ul></div><div className="rounded-2xl bg-horizon-navy p-8 text-white"><h2 className="text-2xl font-bold">Typical pilot components</h2><ul className="mt-5 space-y-3 text-slate-200"><li>AI readiness baseline</li><li>Stakeholder / use-case discovery</li><li>Prompt Mastery learning materials</li><li>Self-paced Academy lessons</li><li>Live workshop or working session</li><li>Role-specific workflow exercise</li><li>Completion assessment and certificates</li><li>Adoption findings and implementation roadmap</li></ul><p className="mt-6 text-sm text-slate-300">Participant count, platform scope, technical implementation, delivery method, price, and customization are defined in the final proposal.</p><a href="/organizations/partnership-inquiry" className="mt-7 inline-block rounded-md bg-horizon-gold px-5 py-3 font-bold text-horizon-navy">Request Pilot Proposal</a></div></div></section>
</>}
