"use client";
import { FormEvent, useState } from "react";
import { submitReadinessAssessment } from "@/lib/actions/corporate";

const questions: [string,string][] = [
 ["currentUsage","How consistently are employees using approved AI tools to complete real work?"], ["formalTraining","How much structured AI training and enablement has your workforce received?"],
 ["aiPolicy","How clear are your organization’s AI-use guidelines, approved-tool expectations, and human-review responsibilities?"], ["promptingConfidence","How confident are employees at giving AI clear instructions and adapting prompts to business context?"],
 ["verificationPractice","How consistently do employees verify important AI outputs before using them in decisions or deliverables?"], ["workflowIntegration","How well is AI integrated into repeatable workflows, knowledge access, or business processes?"],
 ["leadershipReadiness","How prepared are leaders to sponsor use cases, guide responsible adoption, and measure business outcomes?"]
];
export default function ReadinessAssessmentForm(){
 const [result,setResult]=useState<{ok?:boolean;error?:string;score?:number;level?:string}>({}); const [pending,setPending]=useState(false);
 async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setResult({});const fd=new FormData(e.currentTarget);const r=await submitReadinessAssessment({organizationName:String(fd.get("organizationName")||""),contactName:String(fd.get("contactName")||""),email:String(fd.get("email")||""),organizationSize:String(fd.get("organizationSize")||""),currentUsage:String(fd.get("currentUsage")||""),formalTraining:String(fd.get("formalTraining")||""),aiPolicy:String(fd.get("aiPolicy")||""),promptingConfidence:String(fd.get("promptingConfidence")||""),verificationPractice:String(fd.get("verificationPractice")||""),workflowIntegration:String(fd.get("workflowIntegration")||""),leadershipReadiness:String(fd.get("leadershipReadiness")||""),topPriority:String(fd.get("topPriority")||""),website:String(fd.get("website")||"")});setResult(r);setPending(false)}
 if(result.ok) return <div className="rounded-2xl bg-horizon-navy p-8 text-white sm:p-10"><p className="text-sm font-bold uppercase tracking-wider text-horizon-gold">Your AI Readiness Result</p><p className="mt-3 text-5xl font-extrabold">{result.score}/100</p><h2 className="mt-3 text-2xl font-bold">{result.level}</h2><p className="mt-4 max-w-2xl text-slate-200">This directional score is a starting point, not an audit. Next Horizon can use your responses to recommend a path across workforce enablement, use-case discovery, implementation planning, and adoption support.</p><a href="/organizations/partnership-inquiry" className="mt-7 inline-block rounded-md bg-horizon-gold px-6 py-3 font-bold text-horizon-navy">Discuss Your Adoption Plan</a></div>;
 return <form onSubmit={onSubmit} className="grid gap-7 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><input name="website" className="hidden" tabIndex={-1}/><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Organization<input required name="organizationName" className="mt-2 w-full rounded-md border p-3 font-normal"/></label><label className="text-sm font-semibold">Contact name<input required name="contactName" className="mt-2 w-full rounded-md border p-3 font-normal"/></label><label className="text-sm font-semibold">Business email<input required type="email" name="email" className="mt-2 w-full rounded-md border p-3 font-normal"/></label><label className="text-sm font-semibold">Organization size<select name="organizationSize" className="mt-2 w-full rounded-md border p-3 font-normal"><option value="">Select</option><option>1–25</option><option>26–100</option><option>101–500</option><option>501–2,000</option><option>2,001+</option></select></label></div>
 {questions.map(([name,label])=><fieldset key={name}><legend className="font-semibold text-horizon-navy">{label}</legend><div className="mt-3 flex flex-wrap gap-2">{[1,2,3,4,5].map(n=><label key={n} className="cursor-pointer rounded-md border border-slate-300 px-4 py-2 text-sm"><input required type="radio" name={name} value={n} className="mr-2"/>{n}</label>)}</div><p className="mt-2 text-xs text-slate-500">1 = not yet established · 5 = consistently established</p></fieldset>)}
 <label className="font-semibold">What is your organization’s top AI priority right now?<textarea name="topPriority" rows={4} className="mt-2 w-full rounded-md border p-3 font-normal"/></label>{result.error&&<p className="text-sm font-semibold text-red-700">{result.error}</p>}<button disabled={pending} className="rounded-md bg-horizon-blue px-6 py-3.5 font-semibold text-white hover:bg-horizon-navy disabled:opacity-60">{pending?"Calculating…":"Get My AI Readiness Score"}</button></form>
}
